<#
.SYNOPSIS
    Builds the DATUM MSI.

.DESCRIPTION
    Publishes the orchestrator and shell, harvests the web bundle, and produces
    dist\DATUM.msi.

    The UI assets are harvested rather than declared because Vite content-hashes their
    filenames on every build (index-BLP-KLDC.js and so on). A static manifest would go
    stale the first time anyone changed a stylesheet, and the installer would silently
    ship an index.html pointing at assets that are not in the package: an app that
    installs cleanly and then renders a blank window.

    This file is deliberately pure ASCII. Windows PowerShell 5.1 reads .ps1 as ANSI, and
    a stray em dash or box-drawing character breaks its parser before the script runs.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File installers\build.ps1
#>
[CmdletBinding()]
param(
    [string]$Configuration = 'Release',
    [string]$OutputDir = 'dist'
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
Set-Location $repo

$publishRoot = Join-Path $repo "$OutputDir\publish"
$uiDist      = Join-Path $repo 'ui\dist'
$harvested   = Join-Path $PSScriptRoot 'UiAssets.g.wxs'

# --- prerequisites ----------------------------------------------------------

if (-not (Get-Command wix -ErrorAction SilentlyContinue)) {
    throw "The WiX CLI is not installed. Run: dotnet tool install --global wix --version 4.0.5"
}

if (-not (Test-Path $uiDist)) {
    throw "ui\dist not found. Run 'npm --prefix ui run build' first. The installer cannot ship a UI that has not been built."
}

# --- publish ----------------------------------------------------------------

Write-Host 'Publishing orchestrator...' -ForegroundColor Cyan
dotnet publish src\DATUM.Orchestrator\DATUM.Orchestrator.csproj `
    -c $Configuration -r win-x64 --self-contained false `
    -o "$publishRoot\orchestrator" --nologo | Out-Null

Write-Host 'Publishing Studio shell...' -ForegroundColor Cyan
dotnet publish src\DATUM.Studio\DATUM.Studio.csproj `
    -c $Configuration -r win-x64 --self-contained false `
    -o "$publishRoot\studio" --nologo | Out-Null

# --- harvest the web bundle -------------------------------------------------

Write-Host 'Harvesting UI assets...' -ForegroundColor Cyan

$assets = Get-ChildItem -Path $uiDist -Recurse -File
if ($assets.Count -eq 0) { throw "ui\dist is empty." }

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('<?xml version="1.0" encoding="utf-8"?>')
$lines.Add('<!-- GENERATED by installers\build.ps1. Do not edit; regenerated on every build. -->')
$lines.Add('<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">')
$lines.Add('  <Fragment>')
$lines.Add('    <ComponentGroup Id="UiFiles" Directory="UIFOLDER">')

$i = 0
foreach ($asset in $assets) {
    $i++
    $relative = $asset.FullName.Substring($uiDist.Length).TrimStart('\')
    $subdir = [System.IO.Path]::GetDirectoryName($relative)

    # Component ids must be valid identifiers and unique. Indexing keeps them stable
    # without depending on the content hash in the filename.
    $id = "UiAsset$i"
    $source = [System.Security.SecurityElement]::Escape($asset.FullName)

    if ([string]::IsNullOrEmpty($subdir)) {
        $lines.Add("      <Component Id=`"$id`" Guid=`"*`">")
    } else {
        $safe = [System.Security.SecurityElement]::Escape($subdir)
        $lines.Add("      <Component Id=`"$id`" Guid=`"*`" Subdirectory=`"$safe`">")
    }

    $lines.Add("        <File Id=`"${id}File`" Source=`"$source`" KeyPath=`"yes`" />")
    $lines.Add('      </Component>')
}

$lines.Add('    </ComponentGroup>')
$lines.Add('  </Fragment>')
$lines.Add('</Wix>')

Set-Content -Path $harvested -Value $lines -Encoding UTF8
Write-Host "  $($assets.Count) asset(s) harvested" -ForegroundColor DarkGray

# --- build ------------------------------------------------------------------

Write-Host 'Building MSI...' -ForegroundColor Cyan
New-Item -ItemType Directory -Force -Path (Join-Path $repo $OutputDir) | Out-Null

$msi = Join-Path $repo "$OutputDir\DATUM.msi"

wix build `
    (Join-Path $PSScriptRoot 'DATUM.wxs') `
    $harvested `
    -o $msi `
    -arch x64 `
    -ext WixToolset.UI.wixext `
    -d PublishDir="$publishRoot\orchestrator" `
    -d StudioDir="$publishRoot\studio"

if (-not (Test-Path $msi)) { throw 'wix build did not produce an MSI.' }

$size = [math]::Round((Get-Item $msi).Length / 1KB, 1)
Write-Host "MSI built: $msi ($size KB)" -ForegroundColor Green
